CREATE TABLE GIANTS (
    ID                   VARCHAR(36)   NOT NULL,
    FIRST_NAME           VARCHAR(50)   NOT NULL,
    LAST_NAME            VARCHAR(50)   NOT NULL,
    GENDER               VARCHAR(1)    NOT NULL
);

INSERT INTO GIANTS (ID, FIRST_NAME, LAST_NAME, GENDER)
VALUES ('6ebc875e-5fa8-4c96-9841-8d3ad042f7b9', 'Claude', 'Shannon', 'M');
INSERT INTO GIANTS (ID, FIRST_NAME, LAST_NAME, GENDER)
VALUES ('6ebc875e-5fa8-4c96-9841-8d3ad042f7c9', 'Alan', 'Turing', 'M');